language: csharp
solution: src/NCypher.sln
install:
    - nuget restore src/NCypher.sln
    - nuget install NUnit.Runners -OutputDirectory testrunner
script:
    - xbuild /p:Configuration=Release src/NCypher.sln
    - mono ./testrunner/NUnit.Console.*/tools/nunit3-console.exe ./src/NCypher.Tests/bin/Release/NCypher.Tests.dll
notifications:
    email: false